services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    networks:
      - docker_network

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    expose:
      - "9000"
    env_file:
      - ../.env
    networks:
      - docker_network
    volumes:
      - www-data:/var/www/html

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    expose:
      - "3306"
    networks:
      - docker_network
    env_file:
      - ../.env
    volumes:
      - mariadb_database:/var/lib/mysql 

volumes: 
  mariadb_database:
  www-data:

networks:
  docker_network:
    driver: bridge