services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    volumes:
      - www-data:/var/www/html 
    ports:
      - "443:443"
    networks:
      - docker_network

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    expose:
      - "9000"
    env_file:
      - ../.env
    secrets:
      - db_password
      - credentials   
    networks:
      - docker_network
    volumes:
      - www-data:/var/www/html

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    expose:
      - "3306"
    networks:
      - docker_network
    env_file:
      - ../.env
    secrets:
      - db_password
      - db_root_password
    volumes:
      - mariadb_database:/var/lib/mysql 

volumes: 
  mariadb_database:
  www-data:

networks:
  docker_network:
    driver: bridge

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  credentials:
    file: ../secrets/credentials.txt