services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    networks:
      - bridge_network

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    ports:
      - 9000:9000
    # volumes :
    #   - ./php:/var/www/html
    networks:
      - docker_network

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    expose:
      - "3306"
    networks:
      - docker_network
    env_file:
      - ../.env

networks:
  docker_network:
    driver: bridge